[package]
name = "skp-validator-actix"
description = "Actix Web integration for skp-validator - high-performance validation for Actix services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
actix-web = "4.12.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
skp-validator-core = { workspace = true }
futures-util = "0.3.31"

[features]
default = ["serde"]
serde = ["skp-validator-core/serde"]

[dev-dependencies]
actix-rt = "2.11.0"
skp-validator = { path = "../skp-validator", features = ["derive"] }
